// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKu8i20jdoRSUZvCFUXt1mBUNxrc_T_uQ',
    appId: '1:490494751564:web:4a703b4fb83f5f1ad495e9',
    messagingSenderId: '490494751564',
    projectId: 'roberts-web-apps',
    authDomain: 'roberts-web-apps.firebaseapp.com',
    storageBucket: 'roberts-web-apps.firebasestorage.app',
    measurementId: 'G-XV176WNLG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvfkFCLhzMkP_C6kQPWx56GeQep-robmQ',
    appId: '1:490494751564:android:78b588b08319d801d495e9',
    messagingSenderId: '490494751564',
    projectId: 'roberts-web-apps',
    storageBucket: 'roberts-web-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_qEYe2CxBf7HkR12N0dvn0L_ayzWs2EQ',
    appId: '1:490494751564:ios:bd50c6137af9cb43d495e9',
    messagingSenderId: '490494751564',
    projectId: 'roberts-web-apps',
    storageBucket: 'roberts-web-apps.firebasestorage.app',
    iosBundleId: 'com.bellevueopoly.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_qEYe2CxBf7HkR12N0dvn0L_ayzWs2EQ',
    appId: '1:490494751564:ios:bd50c6137af9cb43d495e9',
    messagingSenderId: '490494751564',
    projectId: 'roberts-web-apps',
    storageBucket: 'roberts-web-apps.firebasestorage.app',
    iosBundleId: 'com.bellevueopoly.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKu8i20jdoRSUZvCFUXt1mBUNxrc_T_uQ',
    appId: '1:490494751564:web:4a703b4fb83f5f1ad495e9',
    messagingSenderId: '490494751564',
    projectId: 'roberts-web-apps',
    authDomain: 'roberts-web-apps.firebaseapp.com',
    storageBucket: 'roberts-web-apps.firebasestorage.app',
    measurementId: 'G-XV176WNLG0',
  );

}